# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ale.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(594, 495)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.toolButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.toolButton.setGeometry(QtCore.QRect(9, 396, 25, 19))
        self.toolButton.setObjectName("toolButton")
        self.radioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButton.setGeometry(QtCore.QRect(9, 447, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(190, 420, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 420, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateEdit = QtWidgets.QDateEdit(self.dockWidgetContents)
        self.dateEdit.setGeometry(QtCore.QRect(9, 421, 81, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.progressBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.progressBar.setGeometry(QtCore.QRect(9, 342, 108, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.progressBar_2.setGeometry(QtCore.QRect(9, 369, 108, 21))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdNumber.setGeometry(QtCore.QRect(120, 340, 55, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setLineWidth(2)
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setProperty("value", 5.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdNumber_2.setGeometry(QtCore.QRect(180, 340, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdNumber_3.setGeometry(QtCore.QRect(250, 340, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdNumber_4.setGeometry(QtCore.QRect(320, 340, 64, 23))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.dockWidgetContents)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 10, 551, 301))
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalSlider = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 380, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.toolButton.setText(_translate("DockWidget", "..."))
        self.radioButton.setText(_translate("DockWidget", "RadioButton"))
        self.pushButton.setText(_translate("DockWidget", "PushButton"))
        self.pushButton_2.setText(_translate("DockWidget", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DockWidget = QtWidgets.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())
